### ISSUE TITLE
[BUG] Add formula bugged

### ISSUE THREAD

**Issue by kdanzer-tgm** [Local-Admin-BurgerKing/core#29]
**Add formula only adds to column table**
When adding a formula it only gets added in the column table but not in the formula table.

**To Reproduce**
1. Execute following code:
```java
public static void main(String[] args) throws IOException, SQLException {
	Database.init("localhost:YourPort", "YourUser", "YourUserPassword");
	FormulaManager.addDailyformula(new Formula("formula1", "ADD", "", "", (byte) 0), "A description for formula1");
	}
``` 
2. Error: 
```java
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [insert into `local_admin`.`formula` (`name`, `operator`, `column1`, `column2`, `percent`) values (?, ?, ?, ?, ?)]; Cannot add or update a child row: a foreign key constraint fails
	at org.jooq_3.12.1.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2717)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:206)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:177)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:173)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:161)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:156)
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:176)
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:152)
	at com.finance.manager.FormulaManager.addDailyformula(FormulaManager.java:31)
	at com.localadmin.test.Test.main(Test.java:26)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1340)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:99)
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeysFetchAdditionalRows(AbstractDMLQuery.java:1095)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:959)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:369)
```
3. In MySQL execute:
```sql
select * from local_admin.column;
select * from local_admin.formula;
```

**Expected behavior**
Should add the formula in the column and in the formula table.

**Actual behavior**
Adds the formula only in the column and throws an error.

**Comment by nbrugger-tgm** [comment]
## Error in test case
The columns of a formula cannot be null or ""
